<Project Sdk="Dalamud.NET.Sdk/14.0.1">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Use_DalamudPackager>false</Use_DalamudPackager>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="LICENSE" />
        <None Remove=".gitignore" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Localization\Strings.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Localization\Strings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.resx</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
